<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Description>Implements CK.AspNet.Auth.WebFrontAuthMiddleware CK.AspNet.Auth.WebFrontAuthService abstract base class.</Description>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CK.Auth.Abstractions" Version="13.0.0--ci.1" />
    <PackageReference Include="CK.AspNet" Version="22.0.0--ci.1" />
  </ItemGroup>
</Project>